const RfData = [
  {
    name: "Ford",
    model: "F150 Raptor",
    color: "Blue",
    year: "06/2020",
    mileAge: "25 256",
    HP: "450",
    transmissionType: "Automatic",
    fuel: "Diesel",
    price: "45 000",
    imageUrls: [""],
  },
  {
    name: "Nissan",
    model: "GT-R",
    color: "Gray",
    year: "09/2023",
    mileAge: "5 486",
    HP: "565",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "158 800 ",
  },
  {
    name: "Mercedes-Benz",
    model: "GLC 400 AMG",
    color: "White",
    year: "12/2021",
    mileAge: "35 713",
    HP: "280",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "55 000",
  },
  {
    name: "BMW",
    model: "I4",
    color: "Black",
    year: "08/2023",
    mileAge: "7 278",
    HP: "250",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "70 000",
  },
  {
    name: "Tesla",
    model: "Model S 90D",
    color: "red",
    year: "08/2022",
    mileAge: "20 914",
    HP: "259",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "90 000",
  },
  {
    name: "Ford",
    model: "Kuga",
    color: "black",
    year: "02/2016",
    mileAge: "25 0716",
    HP: "150",
    transmissionType: "Manual",
    fuel: "Diesel",
    price: "30 000",
  },
  {
    name: "Jaguar",
    model: "F-pace",
    color: "Gray",
    year: "01/2023",
    mileAge: "5 126",
    HP: "380",
    transmissionType: "Automatic",
    fuel: "Hybrid",
    price: "80 000",
  },
  ////////////////////////////////////////////////////////////////
  {
    name: "Mercedes-Benz",
    model: "S 500",
    color: "White",
    year: "03/2021",
    mileAge: "27 424",
    HP: "429",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "100 000",
  },
  {
    name: "BMW",
    model: "I7",
    color: "Black",
    year: "07/2023",
    mileAge: "2 000",
    HP: "536",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "120 000",
  },
  {
    name: "Tesla",
    model: "Model 3",
    color: "red",
    year: "11/2022",
    mileAge: "38 247",
    HP: "201",
    transmissionType: "Automatic",
    fuel: "Diesel",
    price: "38 400",
  },
  {
    name: "Chevrolet",
    model: "Camaro ZL1",
    color: "Yellow",
    year: "10/2019",
    mileAge: "15 500",
    HP: "650",
    transmissionType: "Manual",
    fuel: "Gasoline",
    price: "75 000",
  },
  {
    name: "Audi",
    model: "Q5",
    color: "Silver",
    year: "05/2020",
    mileAge: "18 200",
    HP: "248",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "55 000",
  },
  {
    name: "Honda",
    model: "CR-V",
    color: "Green",
    year: "08/2022",
    mileAge: "12 800",
    HP: "190",
    transmissionType: "Automatic",
    fuel: "Hybrid",
    price: "45 000",
  },
  {
    name: "Toyota",
    model: "Corolla",
    color: "Blue",
    year: "07/2018",
    mileAge: "30 000",
    HP: "132",
    transmissionType: "Manual",
    fuel: "Gasoline",
    price: "30 000",
  },
  ////////////////////////////////////////////////////////////////////////
  {
    name: "Nissan",
    model: "Altima",
    color: "Black",
    year: "09/2021",
    mileAge: "22 400",
    HP: "188",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "35 000",
  },
  {
    name: "Volkswagen",
    model: "Golf GTI",
    color: "White",
    year: "04/2017",
    mileAge: "40 500",
    HP: "220",
    transmissionType: "Manual",
    fuel: "Gasoline",
    price: "28 000",
  },
  {
    name: "Hyundai",
    model: "Santa Fe",
    color: "Red",
    year: "07/2019",
    mileAge: "26 300",
    HP: "235",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "32 000",
  },
  {
    name: "Mazda",
    model: "CX-5",
    color: "Brown",
    year: "09/2020",
    mileAge: "16 700",
    HP: "187",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "27 000",
  },
  {
    name: "Ford",
    model: "Escape",
    color: "Orange",
    year: "08/2022",
    mileAge: "8 900",
    HP: "181",
    transmissionType: "Manual",
    fuel: "Hybrid",
    price: "40 000",
  },
  {
    name: "Kia",
    model: "Sorento",
    color: "Purple",
    year: "01/2021",
    mileAge: "14 600",
    HP: "281",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "38 000",
  },
  {
    name: "Subaru",
    model: "Outback",
    color: "Green",
    year: "12/2020",
    mileAge: "25 800",
    HP: "182",
    transmissionType: "Manual",
    fuel: "Gasoline",
    price: "35 000",
  },
  ////////////////////////////////////////////////////////////////
  {
    name: "Chevrolet",
    model: "Equinox",
    color: "Silver",
    year: "02/2019",
    mileAge: "20 300",
    HP: "170",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "30 000",
  },
  {
    name: "Ford",
    model: "Mustang",
    color: "Red",
    year: "08/2021",
    mileAge: "15 500",
    HP: "450",
    transmissionType: "Manual",
    fuel: "Gasoline",
    price: "50 000",
  },
  {
    name: "Volkswagen",
    model: "Tiguan",
    color: "Gray",
    year: "03/2022",
    mileAge: "17 500",
    HP: "200",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "34 000",
  },
  {
    name: "Audi",
    model: "A3",
    color: "Black",
    year: "11/2019",
    mileAge: "23 800",
    HP: "150",
    transmissionType: "Automatic",
    fuel: "Diesel",
    price: "28 500",
  },
  {
    name: "BMW",
    model: "X5",
    color: "Silver",
    year: "06/2021",
    mileAge: "21 200",
    HP: "300",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "45 000",
  },
  {
    name: "Mercedes-Benz",
    model: "A-Class",
    color: "Blue",
    year: "01/2020",
    mileAge: "19 400",
    HP: "180",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "42 000",
  },
  {
    name: "Toyota",
    model: "Rav4",
    color: "White",
    year: "09/2022",
    mileAge: "12 300",
    HP: "203",
    transmissionType: "Automatic",
    fuel: "Hybrid",
    price: "37 000",
  },
  ////////////////////////////////////////////////////////////////
  {
    name: "Ford",
    model: "Focus",
    color: "Red",
    year: "04/2018",
    mileAge: "28 600",
    HP: "160",
    transmissionType: "Manual",
    fuel: "Gasoline",
    price: "22 000",
  },
  {
    name: "Chevrolet",
    model: "Malibu",
    color: "Brown",
    year: "10/2020",
    mileAge: "15 900",
    HP: "190",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "26 500",
  },
  {
    name: "Honda",
    model: "Accord",
    color: "Purple",
    year: "05/2019",
    mileAge: "24 700",
    HP: "192",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "29 000",
  },
  {
    name: "Nissan",
    model: "Rogue",
    color: "Orange",
    year: "08/2021",
    mileAge: "14 200",
    HP: "170",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "32 000",
  },
  {
    name: "Tesla",
    model: "Model Y",
    color: "Green",
    year: "02/2023",
    mileAge: "5 000",
    HP: "350",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "60 000",
  },
];

export default RfData;
