const RfData = [
  {
    name: "Ford",
    model: "F150 Raptor",
    color: "Blue",
    year: "06/2020",
    mileAge: "25 256",
    HP: "450",
    transmissionType: "Automatic",
    fuel: "Diesel",
    price: "45 000",
    imageUrls: [""],
  },
  {
    name: "Nissan",
    model: "GT-R",
    color: "Grey",
    year: "09/2023",
    mileAge: "5 486",
    HP: "565",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "158 800 ",
  },
  {
    name: "Mercedes-Benz",
    model: "GLC 400 AMG",
    color: "red",
    year: "12/2021",
    mileAge: "35 713",
    HP: "280",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "55 000",
  },
  {
    name: "BMW",
    model: "I4",
    color: "Black",
    year: "08/2023",
    mileAge: "7 278",
    HP: "250",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "70 000",
  },
  {
    name: "TESLA",
    model: "MODEL S 90D",
    color: "red",
    year: "08/2022",
    mileAge: "20 914",
    HP: "259",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "90 000",
  },
  {
    name: "Ferrai",
    model: "GT4C LUSSO V12",
    color: "Grey",
    year: "02/2017",
    mileAge: "37 999",
    HP: "690",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "215 000",
  },
  {
    name: "Jaguar",
    model: "F-pace",
    color: "Grey",
    year: "01/2023",
    mileAge: "5 126",
    HP: "380",
    transmissionType: "Automatic",
    fuel: "Hybrid",
    price: "80 000",
  },
  ////////////////////////////////////////////////////////////////
  {
    name: "Mercedes-Benz",
    model: "Class S 500",
    color: "White",
    year: "03/2021",
    mileAge: "27 424",
    HP: "429",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "100 000",
  },
  {
    name: "BMW",
    model: "I7",
    color: "Black",
    year: "07/2023",
    mileAge: "2 000",
    HP: "536",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "120 000",
  },
  {
    name: "Tesla",
    model: "Model 3",
    color: "red",
    year: "11/2022",
    mileAge: "38 247",
    HP: "201",
    transmissionType: "Automatic",
    fuel: "Diesel",
    price: "38 400",
  },
  {
    name: "Chevrolet",
    model: "Camaro ZL1",
    color: "Yellow",
    year: "10/2019",
    mileAge: "15 500",
    HP: "650",
    transmissionType: "Manual",
    fuel: "Gasoline",
    price: "75 000",
  },
  {
    name: "Audi",
    model: "RS3 Sportback",
    color: "Silver",
    year: "05/2020",
    mileAge: "18 200",
    HP: "248",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "55 000",
  },
  {
    name: "Porsche",
    model: "Panamera S",
    color: "Black",
    year: "08/2019",
    mileAge: "92 000",
    HP: "462",
    transmissionType: "Automatic",
    fuel: "Hybrid",
    price: "74 990",
  },
  {
    name: "Dodge",
    model: "Challenger 2 V8",
    color: "Grey",
    year: "11/2018",
    mileAge: "33 050",
    HP: "707",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "99 990",
  },
  ////////////////////////////////////////////////////////////////////////
  {
    name: "Mercedes-benz",
    model: "Class g 63 ",
    color: "Black",
    year: "09/2019",
    mileAge: "30 827",
    HP: "585",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "189 989",
  },
  {
    name: "Volkswagen",
    model: "Golf GTI",
    color: "White",
    year: "04/2017",
    mileAge: "40 500",
    HP: "220",
    transmissionType: "Manual",
    fuel: "Gasoline",
    price: "29 990",
  },
  {
    name: "Mercedes-Benz",
    model: "AMG GT53",
    color: "Grey",
    year: "07/2020",
    mileAge: "68 000",
    HP: "435",
    transmissionType: "Automatic",
    fuel: "Hybrid",
    price: "95 000",
  },
  {
    name: "Land Rover",
    model: "Defender 110",
    color: "Green",
    year: "09/2020",
    mileAge: "58 201",
    HP: "241",
    transmissionType: "Automatic",
    fuel: "Diesel",
    price: "74 900",
  },
  {
    name: "Maserati",
    model: "Quattroporte V8",
    color: "Grey",
    year: "08/2007",
    mileAge: "83 799",
    HP: "400",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "39 990",
  },
  {
    name: "Audi",
    model: "SQ5 Quattro 3.0",
    color: "Black",
    year: "01/2017",
    mileAge: "155 690",
    HP: "340",
    transmissionType: "Automatic",
    fuel: "Diesel",
    price: "34 990",
  },
  {
    name: "Mercedes-Benz",
    model: "Class E 250",
    color: "Black",
    year: "12/2020",
    mileAge: "25 800",
    HP: "204",
    transmissionType: "Manual",
    fuel: "Gasoline",
    price: "35 000",
  },
  ////////////////////////////////////////////////////////////////
  {
    name: "Tesla",
    model: "Model X ",
    color: "White",
    year: "02/2019",
    mileAge: "69 523",
    HP: "785",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "66 800",
  },
  {
    name: "Ford",
    model: "Mustang V8 5.0",
    color: "Green",
    year: "08/2019",
    mileAge: "6 020",
    HP: "545",
    transmissionType: "Manual",
    fuel: "Gasoline",
    price: "69 900",
  },
  {
    name: "Tesla",
    model: "Model S 100D",
    color: "Grey",
    year: "03/2019",
    mileAge: "43 786",
    HP: "422",
    transmissionType: "Automatic",
    fuel: "Electric",
    price: "63 989",
  },
  {
    name: "Audi",
    model: "S5 V6 3.0",
    color: "Black",
    year: "11/2017",
    mileAge: "23 800",
    HP: "354",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "45 990",
  },
  {
    name: "Maserati",
    model: "Levante 3.0 V6",
    color: "Navy",
    year: "06/2019",
    mileAge: "68 024",
    HP: "350",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "54 990",
  },
  {
    name: "Mercedes-Benz",
    model: "Class E350 ",
    color: "White",
    year: "01/2017",
    mileAge: "19 400",
    HP: "258",
    transmissionType: "Automatic",
    fuel: "Diesel",
    price: "47 990",
  },
  {
    name: "Porsche",
    model: "Cayenne 4.8 V8",
    color: "White",
    year: "09/2014",
    mileAge: "95 760",
    HP: "520",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "37 000",
  },
  ////////////////////////////////////////////////////////////////
  {
    name: "Porsche",
    model: "Cayenne e-Hybrid",
    color: "White",
    year: "04/2018",
    mileAge: "79 900",
    HP: "462",
    transmissionType: "Manual",
    fuel: "Hybrid",
    price: "75 900",
  },
  {
    name: "Dodge",
    model: "Challenger V8",
    color: "Orange",
    year: "10/1970",
    mileAge: "154 700",
    HP: "375",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "59 900",
  },
  {
    name: "Aston Martin ",
    model: "Rapide V12",
    color: "Black",
    year: "05/2011",
    mileAge: "47 800",
    HP: "470",
    transmissionType: "Automatic",
    fuel: "Gasoline",
    price: "71 900",
  },
  {
    name: "Volkswagen",
    model: "Touareg",
    color: "grey",
    year: "08/2021",
    mileAge: "59 666",
    HP: "462",
    transmissionType: "Automatic",
    fuel: "Hybrid",
    price: "69 990",
  },
  {
    name: "Land Rover",
    model: "Defender 130",
    color: "Grey",
    year: "02/2023",
    mileAge: "29 500",
    HP: "300",
    transmissionType: "Automatic",
    fuel: "Diesel",
    price: "130 000",
  },
];

export default RfData;
